# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget, GLLinePlotItem, GLAxisItem
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2736, 1824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.plotobj_Quat_Plot = GLViewWidget(self.centralwidget)
        # self.plotobj_Quat_Plot.setGeometry(QtCore.QRect(10, 10, 700, 700))
        # self.plotobj_Quat_Plot.setObjectName("plotobj_Quat_Plot")
        # self.plotobj_Euler_Plot = GLViewWidget(self.centralwidget)
        # self.plotobj_Euler_Plot.setGeometry(QtCore.QRect(10, 720, 700, 700))
        # self.plotobj_Euler_Plot.setObjectName("plotobj_Euler_Plot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 10, 100, 13))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 720, 100, 13))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.plotobj_strip_chart_1 = PlotWidget(self.centralwidget)
        self.plotobj_strip_chart_1.setGeometry(QtCore.QRect(720, 10, 1000, 200))
        self.plotobj_strip_chart_1.setObjectName("plotobj_strip_chart_1")
        self.plotobj_strip_chart_2 = PlotWidget(self.centralwidget)
        self.plotobj_strip_chart_2.setGeometry(QtCore.QRect(720, 220, 1000, 200))
        self.plotobj_strip_chart_2.setObjectName("plotobj_strip_chart_2")
        self.plotobj_strip_chart_3 = PlotWidget(self.centralwidget)
        self.plotobj_strip_chart_3.setGeometry(QtCore.QRect(720, 430, 1000, 200))
        self.plotobj_strip_chart_3.setObjectName("plotobj_strip_chart_3")
        self.plotobj_strip_chart_4 = PlotWidget(self.centralwidget)
        self.plotobj_strip_chart_4.setGeometry(QtCore.QRect(720, 640, 1000, 200))
        self.plotobj_strip_chart_4.setObjectName("plotobj_strip_chart_4")
        self.plotobj_strip_chart_5 = PlotWidget(self.centralwidget)
        self.plotobj_strip_chart_5.setGeometry(QtCore.QRect(720, 850, 1000, 200))
        self.plotobj_strip_chart_5.setObjectName("plotobj_strip_chart_5")
        self.plotobj_strip_chart_6 = PlotWidget(self.centralwidget)
        self.plotobj_strip_chart_6.setGeometry(QtCore.QRect(720, 1060, 1000, 200))
        self.plotobj_strip_chart_6.setObjectName("plotobj_strip_chart_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1620, 10, 100, 13))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1620, 220, 100, 13))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1620, 430, 100, 13))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1620, 640, 100, 13))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1620, 850, 100, 13))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1620, 1060, 100, 13))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1850, 60, 200, 50))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1850, 10, 200, 50))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2560, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #user added b/c I don't know how to set this inside QtDesigner
        self.label.setStyleSheet("color:white")
        self.label_2.setStyleSheet("color:white")
        self.label_3.setStyleSheet("color:white")
        self.label_4.setStyleSheet("color:white")
        self.label_5.setStyleSheet("color:white")
        self.label_6.setStyleSheet("color:white")
        self.label_7.setStyleSheet("color:white")
        self.label_8.setStyleSheet("color:white")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Quat Plot"))
        self.label_2.setText(_translate("MainWindow", "Euler Plot"))
        self.label_3.setText(_translate("MainWindow", "Accel X"))
        self.label_4.setText(_translate("MainWindow", "Accel Y"))
        self.label_5.setText(_translate("MainWindow", "Accel Y"))
        self.label_6.setText(_translate("MainWindow", "Gyro X"))
        self.label_7.setText(_translate("MainWindow", "Gyro Y"))
        self.label_8.setText(_translate("MainWindow", "Gyro Z"))
        self.pushButton.setText(_translate("MainWindow", "Stop Collection"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
